dotfiles_dir = "dotfiles"

[settings.dots]

foot = { source = "foot/foot.ini", target = ".config/foot/foot.ini" }
AstroNvim = { source = "AstroNvim", target = ".config/nvim" }
fish = { source = "fish", target = ".config/fish" }
sway = { source = "sway", target = ".config/sway" }
waybar = { source = "waybar", target = ".config/waybar" }
tofi = { source = "tofi", target = ".config/tofi" }
ideavim = { source = "ideavim/.ideavimrc", target = ".ideavimrc" }
discord = { source = "discord_updates_shut_up/settings.json", target = ".config/discord/settings.json" }
midnight_enjoyer = { source = "util/midnight_enjoyer.jl", target = ".util/midnight_enjoyer.jl" }

#TODO: figure out privileges. Mb wait for https://github.com/oknozor/toml-bombadil/issues/33
# btrbk = { source = "backups/btrbk/btrbk.conf", target = "/etc/btrbk/btrbk.conf" }
# snapper = { source = "backups/snapper/root", target = "/etc/snapper/configs/root" }

# requires toolkit.legacyUserProfileCustomizations.stylesheets. More info: https://github.com/mbnuq/sidebery/iki/Firefox-Styles-Snippets-(via-userChrome.css)
# waiting for ability to inject variable to path: https://github.com/oknozor/toml-bombadil/issues/258
firefox_style = { source = "firefox/userChrome.css", target = ".mozilla/firefox/rip6alsd.default-release/chrome/userChrome.css" }
# sidebery = {source="firefox/sidebery.json", target="???"}
