format = """
[  $character](bg:#30333d fg:#a3b8d6)\
[](bg:#30333d fg:#707070)\
$directory\
$git_branch\
$git_status\
[](#30333d)\
$fill\
[](#30333d)\
$status\
$cmd_duration\
[ ](bg:#30333d fg:#909090)\
$username\
$hostname\
[ ](bg:#30333d fg:#909090)\
$time\
[ ](bg:#30333d fg:#567676)"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#b69676 bg:#30333d"
style_root = "fg:#b69676 bg:#30333d"
format = '[$user]($style)'
disabled = false

[status]
style = 'bg:#30333d'
symbol = '[✘ ](fg:red bg:#30333d)'
success_symbol = '[✔ ](fg:green bg:#30333d)'
format = '[[$signal_name ](fg:red bg:#30333d)$symbol]($style)'
map_symbol = false
disabled = false

[character]
success_symbol = 'I'
error_symbol = 'I'
vimcmd_symbol = 'N'

[cmd_duration]
min_time = 1
style = 'bg:#30333d fg:#909090'
format = '[ took [$duration](bold fg:#909090 bg:#30333d)  ]($style)'

[hostname]
ssh_only = false
style = 'fg:#b69676 bg:#30333d'
format = '[@$hostname ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#30333d"
disabled = true      # Disabled by default

[directory]
style = "fg:#0a96d6 bg:#30333d"
format = "[  $path ]($style)"
truncation_length = 9
truncation_symbol = "…/"
truncate_to_repo = true
home_symbol = '~'

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
#"~/" = "~./"
"~" = " ~"


[fill]
symbol = ' '
#symbol = '・'

[c]
symbol = ""
style = "bg:#30333d"
format = '[ $symbol ]($style)'

[docker_context]
symbol = " "
style = "bg:#30333d"
format = '[ $symbol $context ]($style) $path'

[git_branch]
style = "fg:#56b60a bg:#30333d"
format = '[](fg:#707070 bg:#30333d)[  ](fg:#56b60a bg:#30333d)[ $branch ](bold $style)'

[git_status]
style = "fg:#0a96d6 bg:#30333d"
conflicted = "~"
up_to_date = " "
untracked = "?${count}"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "*"
modified = " ${count}"
staged = '[++\($count\)](fg:#56b60a bg:#30333d)'
renamed = " "
deleted = " ${count}"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "go"
style = "fg:#FFFFFF bg:#30333d"
format = '[ $symbol ](bold $style)'

[java]
symbol = ""
style = "fg:#0a96d6 bg:#30333d"
format = '[ $symbol ]($style)'

[nodejs]
symbol = ""
style = "fg:#0a96d6 bg:#30333d"
format = '[ $symbol ]($style)'

[python]
# Display the version of python from inside a local venv.
#
# Note this will only work when the venv is inside the project and it will only
# work in the directory that contains the venv dir but maybe this is ok?
symbol = ' '
style = "fg:#0a96d6 bg:#30333d"
format = '[ $symbol ]($style)'

[rust]
symbol = ""
style = "fg:#0a96d6 bg:#30333d"
format = '[ $symbol ]($style)'

[time]
disabled = false
time_format = "%R"              # Hour:Minute Format
style = "bg:#30333d fg:#567676"
format = '[$time ]($style)'
